name: epi-clock
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pyyaml
  - joblib
  - requests
  - biopython
  - beautifulsoup4
  - lxml
  - tqdm
  - pip
  - pip:
    - GEOparse
    - xmltodict
    - pubmed-parser
