name: epi-clock
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - jupyterlab
  - pip:
      - pyreadr
      - pyarrow
      - polars
      - lifelines
      - pingouin
